/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package firstgradleproject;

public class App {
    public String getGreeting() {
        return "Hello World! From my first Gradle Project";
    }
/*Hello this is my comment just for commit */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("New Line - Hello");
        
    }
}
